modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/spacemex/SkillExpNotifier/issues"
license = "MIT"

[[mods]]
modId = "skillexpnotifier"
version = "${version}"
displayName = "SkillExpNotifier"
authors = "Space_Mex"
description = '''
A Simple Mod For Displaying A Toast For Pufferfish Skills Api
'''
#logoFile = ""
displayURL = "https://www.curseforge.com/minecraft/mc-mods/skillexpnotifier"

[[dependencies.skillexpnotifier]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.skillexpnotifier]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.skillexpnotifier]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.skillexpnotifier]]
modId = "puffish_skills"
mandatory = true
versionRange = "[0.16.0,)"
