modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/spacemex/SkillExpNotifier/issues"

[[mods]]
modId = "skillexpnotifier"
version = "${actual_version}"
displayName = "SkillExpNotifier"
authors = "Space_Mex"
description = '''
A simple mod for displaying a toast for Pufferfish's Skills API.
'''
logoFile = "assets/skillexpnotifier/icon.png"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/skillexpnotifier"

[[dependencies.skillexpnotifier]]
modId = "neoforge"
type = "required"
versionRange = "[26.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.skillexpnotifier]]
modId = "minecraft"
type = "required"
versionRange = "[26.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.skillexpnotifier]]
modId = "architectury"
type = "required"
versionRange = "[21.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.skillexpnotifier]]
modId = "puffish_skills"
type = "required"
versionRange = "[0.16.0,)"
ordering = "NONE"
side = "BOTH"