modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/spacemex/SkillExpNotifier/issues"
license = "MIT"

[[mods]]
modId = "skillexpnotifier"
version = "${actual_version}"
displayName = "SkillExpNotifier"
authors = "Space_Mex"
description = '''
A Simple Mod For Displaying A Toast For Pufferfish Skills Api
'''
logoFile = "assets/skillexpnotifier/icon.png"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/skillexpnotifier"

[[dependencies.skillexpnotifier]]
modId = "neoforge"
type = "required"
versionRange = "[21.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.skillexpnotifier]]
modId = "minecraft"
type = "required"
versionRange = "[1.2.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.skillexpnotifier]]
modId = "architectury"
type = "required"
versionRange = "[14.0.4,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.skillexpnotifier]]
modId = "puffish_skills"
type = "required"
versionRange = "[0.16.0,)"
ordering = "NONE"
side = "BOTH"
