plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }

    bundledLibraries {
        canBeResolved = true
        canBeConsumed = false
    }

    compileClasspath.extendsFrom common, bundledLibraries
    runtimeClasspath.extendsFrom common, bundledLibraries
    developmentFabric.extendsFrom common, bundledLibraries
}

dependencies {
    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"

    implementation "dev.architectury:architectury-fabric:${rootProject.architectury_api_version}"
    implementation "net.puffish:skillsmod:${rootProject.skill_api}:fabric"

    bundledLibraries "org.yaml:snakeyaml:${rootProject.snake_version}"
    bundledLibraries "com.github.spacemex:SimpleConfigApi:${rootProject.simple_config_version}"

    common(project(':common')) {
        transitive = false
    }

    shadowBundle(project(
            path: ':common',
            configuration: 'transformProductionFabric'
    )) {
        transitive = false
    }
}

tasks.named('processResources') {
    inputs.property 'version', project.version
    inputs.property 'actual_version', rootProject.actual_version

    filesMatching('fabric.mod.json') {
        expand(
                version: project.version,
                actual_version: rootProject.actual_version
        )
    }
}

tasks.named('jar') {
    archiveClassifier.set('dev')
}

tasks.named('shadowJar') {
    configurations = [
            project.configurations.shadowBundle,
            project.configurations.bundledLibraries
    ]

    relocate(
            'org.yaml.snakeyaml',
            'com.github.spacemex.skillexpnotifier.libs.snakeyaml'
    )

    relocate(
            'com.github.spacemex.SimpleConfigApi',
            'com.github.spacemex.skillexpnotifier.libs.simpleconfigapi'
    )

    archiveClassifier.set('')
}

tasks.named('sourcesJar') {
    from project(':common').sourceSets.main.allSource
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named('assemble') {
    dependsOn tasks.named('shadowJar')
}