# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true

# Mod properties
actual_version = 8.1.7
mod_version = 8.1.7-HOTFIX
maven_group = com.github.spacemex
archives_name = skillexpnotifier
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.1

architectury_api_version = 20.0.2
fabric_loader_version = 0.18.5
fabric_api_version = 0.144.1+26.1
neo_version = 26.1.0.1-beta

skill_api= 0.17.3+26.1

snake_version= 2.4
simple_config_version= manual-5
