# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true

# Mod properties
actual_version = 9.0.0
mod_version = 9.0.0
maven_group = com.github.spacemex
archives_name = skillexpnotifier
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.2

architectury_api_version = 21.0.2
fabric_loader_version = 0.18.5
fabric_api_version = 0.152.1+26.2
neo_version = 26.2.0.0-beta

skill_api= 0.18.0+26.2

snake_version= 2.4
simple_config_version= manual-5
